[package]
name = "rich-prompt-plugin"
version = "0.2.3"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
yosh-plugin-sdk = { git = "https://github.com/k-ymmt/yosh", tag = "v0.2.1" }

[package.metadata.component]
package = "k-ymmt:rich-prompt-plugin"

[package.metadata.component.target]
path = "wit"
world = "plugin-world"

[profile.release]
opt-level = "s"
lto = true
strip = true
panic = "abort"
